language: yml
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - coverage run ./bin/Run.class
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7
after_success: 
  - codecov --token=cf0f0e15-914b-4569-868f-00718f7f7048
